package com.easy2excel.entity;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;


@DynamoDBTable(tableName="customers")
public class Customers {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private double id;

    @DynamoDBAttribute
    private String firstname;

    @DynamoDBAttribute
    private String lastname;

    @DynamoDBAttribute
    private String gender;

    @DynamoDBAttribute
    private String country;

    public Double getId() {
        return id;
    }

    public void setId(double id) {
        this.id = id;
    }

    public String getFirstname() {
        return firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getLastname() {
        return lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    

}
